### ISSUE TITLE
Already detected problems on Antonios source

### ISSUE THREAD

**Issue by l00mi** [RubenVerborgh/SPARQL-Parser#1]
Hi @RubenVerborgh,
I just want to draw your attention on some issues I could already detected with the version you base this package on through some burns in real life testing ...
1. a small language tag recognition error: https://github.com/l00mi/rdfstore-js/commit/d1b39188f7369107f4b98537ba7148755593a4a2
2. some troubles with quote escaping: https://github.com/l00mi/rdfstore-js/commit/e592250cd06d4251e503a5def7814e8642870ddd

Hope this helps head-jump-over this hurdles more easily.

**Comment by RubenVerborgh** [comment]
Thanks a lot for this, I will look into that.
One reason I moved the code to a separate package is precisely to be able to fix such issues independently of the base source.

**Comment by ktk** [comment]
Great thanks Ruben, looking forward to that. Should I migrate my issues as well, had some proposals for extending some SPARQL functionality.

**Comment by RubenVerborgh** [comment]
@ktk I'm a bit unsure at the moment; merges might get hard as I decided to import only a subtree of rdfstore-js. Maybe start by linking issues in this comment thread?

**Comment by ktk** [comment]
@RubenVerborgh I just talked with @l00mi and he told me he is happy to help. Would pulls on your forked code help?

**Comment by RubenVerborgh** [comment]
Pulls on the forked code would be excellent! Be sure to always include some kind of test, so I can verify. At the moment, an example query in `/queries` and corresponding parse tree in `/test/parsedQueries` will be sufficient.

**Comment by RubenVerborgh** [comment]
With the release of [SPARQL.js](https://github.com/RubenVerborgh/SPARQL.js), this repository is now obsolete.
